### ISSUE TITLE
Ошибка при создании ордера

### ISSUE THREAD

**Issue by brandeurs** [blackchestnut/invest_tinkoff#1]
Добрый день. Все отлично работает, кроме создания ордера.

client.create_order(account_id:account_id, figi:figi, quantity: 1, price: price, direction:1, order_type:1, order_id: '1')

и выдает #<struct InvestTinkoff::V2::Response payload={"code"=>3, "message"=>nil, "description"=>nil}, http_code=400>

Как не пытался, не понимаю в чем тут причина. Все переменные проверил на других запросах. account_id, figi. На других - работает. Даже отмена работает, но создание нет.

**Comment by blackchestnut** [comment]
@brandeurs день, добрый.
хм, странно, у меня отрабатывает штатно. Вот мой код создания ордера:
```ruby
  def create_broker_order figi:, order:
    response = client.create_order(
      account_id: BROKER_ACCOUNT_ID,
      figi: figi,
      quantity: order.quantity,
      price: order.price,
      direction: InvestTinkoff::V2::OrderDirection::BUY,
      order_type: InvestTinkoff::V2::OrderType::LIMIT,
      order_id: "oxx=#{order.id}"
    )
  ...
```
Обратите внимание на `order_id`, я сначала хотел использовать просто свой id локального ордера, но такое ощущение, что у tinkoff в базе это уникальный индекс по всем order_id без учета брокерского счета, поэтому я добавил `oxx=ID`. И у меня начали проходить запросы.

Могу вам предложить добавить что-то вроде `blablabla-ВАШ_ID` вдруг поможет.
