### ISSUE TITLE
Не работает ни маркет ни лимит order

### ISSUE THREAD

**Issue by brandeurs** [blackchestnut/invest_tinkoff#3]
client.create_order(
  account_id: 'ВАШ_ID_СЧЁТА',
  figi: 'BBG000BL9C59',
  quantity: 1,
  price: 11.35,
  direction: InvestTinkoff::V2::OrderDirection::BUY,
  order_type: InvestTinkoff::V2::OrderType::LIMIT,
  order_id: 'ВАШ_ВНУТРЕННИЙ_ID_ЗАЯВКИ'
)

order_id - генерю по дате и секундам уникальный
ошибка 400 и все. Остальное работает.

**Comment by blackchestnut** [comment]
@brandeurs хм, странно... на текущей версии библиотеки проверил
```ruby
client.create_order(account_id: '***', figi: 'FUTSI0923000', quantity: 1, price: 86000, direction: InvestTinkoff::V2::OrderDirection::BUY, order_type: InvestTinkoff::V2::OrderType::LIMIT, order_id: 'test_1_20_06_2023')
```

### Результат
```ruby
=> #<struct InvestTinkoff::V2::Response
 payload=
  {"orderId"=>"1892948522941182087",
   "executionReportStatus"=>"EXECUTION_REPORT_STATUS_NEW",
   "lotsRequested"=>"1",
   "lotsExecuted"=>"0",
   "initialOrderPrice"=>{"currency"=>"rub", "units"=>"86000", "nano"=>0},
   "executedOrderPrice"=>{"currency"=>"rub", "units"=>"0", "nano"=>0},
   "totalOrderAmount"=>{"currency"=>"rub", "units"=>"0", "nano"=>0},
   "initialCommission"=>{"currency"=>"rub", "units"=>"34", "nano"=>400000000},
   "executedCommission"=>{"currency"=>"rub", "units"=>"0", "nano"=>0},
   "aciValue"=>{"currency"=>"", "units"=>"0", "nano"=>0},
   "figi"=>"FUTSI0923000",
   "direction"=>"ORDER_DIRECTION_BUY",
   "initialSecurityPrice"=>{"currency"=>"rub", "units"=>"86000", "nano"=>0},
   "orderType"=>"ORDER_TYPE_LIMIT",
   "message"=>"",
   "initialOrderPricePt"=>{"units"=>"86000", "nano"=>0},
   "instrumentUid"=>"1f9e6a2e-aff1-4e9c-8b22-17de45443e2b"},
 http_code=200>
```

P.S. Сделал ордер так, чтобы он сразу исполнился, т.к. цена, по которой хочу купить, выше чем текущая... результат: 

![Monosnap 2023-06-20 21-28-41](https://github.com/blackchestnut/invest_tinkoff/assets/2400100/1e2a776e-4eb1-435c-9835-912c30c9f76c)

**Comment by blackchestnut** [comment]
@brandeurs попробую влить и протестировать изменения #4 от @SRadyukov возможно это влияет на ваш случай, но предполагаю, что не в этом причина

**Comment by blackchestnut** [comment]
@brandeurs да, как и предполагалось, эти изменения не повлияли на результат в моих тестах... Для больше информации вам нужно прислать сообщение об ошибке, которое возвращает Тинькофф. Например:
```ruby
=> #<struct InvestTinkoff::V2::Response payload={"code"=>3, "message"=>"not enough assets for a margin trade", "description"=>"30042"}, http_code=400>
```

**Comment by blackchestnut** [comment]
@brandeurs Эх, час жизни у меня забрали... смотрите ошибки и требования к бумаге... ошибка у вас скорее всего - "only for qualified investors"

**Comment by blackchestnut** [comment]
@brandeurs Эх, вы видимо просто в лоб скопировали пример... обращайте внимание на ошибки и требования к бумаге... ошибка у вас скорее всего - "only for qualified investors". Цена то же могла поменяться, тогда ошибка была бы другой

**Comment by brandeurs** [comment]
Доброе утро.
Я же посылал этот вопрос в чат. И ребята сказали написать вам, потому что ошибка в quotation.
Последняя версия гем - перестала подключаться к клиенту. Возвращаю старую - работает. Новая - ошибка.
У меня и маржа включена и статус квалифицированного инвестора. Поэтому ошибка явно не в этом.

Проверьте пожалуйста.

**Comment by brandeurs** [comment]
В старой версии ответ гема :: client.accounts

#<struct InvestTinkoff::V2::Response
 payload=
  {"accounts"=>
    [{"id"=>”****",
      "type"=>"ACCOUNT_TYPE_TINKOFF",
      "name"=>"Брокерский счёт",
      "status"=>"ACCOUNT_STATUS_OPEN",
      "openedDate"=>"2019-11-28T00:00:00Z",
      "closedDate"=>"1970-01-01T00:00:00Z",
      "accessLevel"=>"ACCOUNT_ACCESS_LEVEL_FULL_ACCESS"}]},


Новая версия гема
---
gem install invest_tinkoff
Fetching invest_tinkoff-0.9.6.7.gem
Successfully installed invest_tinkoff-0.9.6.7
1 gem installed

client.accounts
ArgumentError: wrong number of arguments (given 2, expected 1)
from /Users/adm/.rvm/gems/ruby-3.1.2/gems/json-1.8.6/lib/json/common.rb:155:in `initialize'

**Comment by brandeurs** [comment]
client.create_order(account_id: account_id, figi: 'FUTSI0923000', quantity: 1, price: 86000, direction: InvestTinkoff::V2::OrderDirection::BUY, order_type: InvestTinkoff::V2::OrderType::LIMIT, order_id: 'tes1212t1_1_20_06_2023')
=> #<struct InvestTinkoff::V2::Response
 payload={"code"=>3, "message"=>nil, "description"=>nil},
 http_code=400>

Как ни крути - одинаковый ответ на старом. А новый гем - клиента не подключает.

**Comment by blackchestnut** [comment]
@brandeurs Сложно понять в чем у вас дело, попробуйте новый токен создать в тинькофф, может у вас он "протух". На сколько я помню, если не пользоваться несколько месяцев токеном, то он становится не активным.

**Comment by blackchestnut** [comment]
> В старой версии ответ гема :: client.accounts #<struct InvestTinkoff::V2::Response payload= {"accounts"=> [{"id"=>”****", "type"=>"ACCOUNT_TYPE_TINKOFF", "name"=>"Брокерский счёт", "status"=>"ACCOUNT_STATUS_OPEN", "openedDate"=>"2019-11-28T00:00:00Z", "closedDate"=>"1970-01-01T00:00:00Z", "accessLevel"=>"ACCOUNT_ACCESS_LEVEL_FULL_ACCESS"}]}, Новая версия гема --- gem install invest_tinkoff Fetching invest_tinkoff-0.9.6.7.gem Successfully installed invest_tinkoff-0.9.6.7 1 gem installed client.accounts ArgumentError: wrong number of arguments (given 2, expected 1) from /Users/adm/.rvm/gems/ruby-3.1.2/gems/json-1.8.6/lib/json/common.rb:155:in `initialize'

Изменения в последней версии метод `accounts` совсем не затрагивали
https://github.com/blackchestnut/invest_tinkoff/compare/v0.9.6.6...v0.9.6.7
