### ISSUE TITLE
Сломалось подключение в последнем обновлении

### ISSUE THREAD

**Issue by brandeurs** [blackchestnut/invest_tinkoff#6]
Сам клиент - не подключается.

client.accounts
ArgumentError: wrong number of arguments (given 2, expected 1)

Пробую старую версию и все работает.
Обновляю - ошибка.

**Comment by blackchestnut** [comment]
@brandeurs добрый день, я не знаю в чем у вас проблема:
```ruby
token = "t.zRSFOgTqtk..."
client = InvestTinkoff::V2::Client.new token: token
client.accounts

=> #<struct InvestTinkoff::V2::Response
 payload=
  {"accounts"=>
    [{"id"=>"2000*********",
      "type"=>"ACCOUNT_TYPE_TINKOFF",
      "name"=>"Брокерский счёт",
      "status"=>"ACCOUNT_STATUS_OPEN",
      "openedDate"=>"2018-05-23T00:00:00Z",
      "closedDate"=>"1970-01-01T00:00:00Z",
      "accessLevel"=>"ACCOUNT_ACCESS_LEVEL_FULL_ACCESS"}]},
 http_code=200>
```

Проверил на всякий случай версию, что у меня та загружена
```ruby
require 'invest_tinkoff/version'
InvestTinkoff::VERSION
=> "0.9.6.7"
```

**Comment by blackchestnut** [comment]
Изменения в последней версии метод `accounts` совсем не затрагивали
https://github.com/blackchestnut/invest_tinkoff/compare/v0.9.6.6...v0.9.6.7

**Comment by blackchestnut** [comment]
@brandeurs чтобы хоть как-то попытаться воспроизвести вашу проблему, мне нужен полный код вашего скрипта, где вы пытаетесь выполнить это... вот прям полностью, конечно, без token-ов и другой личной информации. Можно просто `rb` файл с подробной инструкцией как его запустить, чтобы я смог это сделать локально.
